### ISSUE TITLE
Set clone depth in Sourcetree?

### ISSUE THREAD

**Issue by mitchellkrogza** [GSoft-SharePoint/Dynamite#32]
Anyone know how to set the clone depth of a repo in SourceTree?

**Comment by Zargath** [comment]
When cloning the repo with SourceTree, the option is available under Advanced Options once you have specified the Source Path.

![image](https://cloud.githubusercontent.com/assets/5606594/25194403/53181ca8-2508-11e7-8266-b9645ce1ac87.png)

**Comment by mitchellkrogza** [comment]
Thanks @Zargath that option does not appear in advanced on SourceTree for MacOS
